# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'IMBDMovies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IMBDMovies
  pod 'Alamofire', '~> 4.7'
  pod 'Argo'
  pod 'SDWebImage', '~> 4.0'
  pod 'ReachabilitySwift'

  target 'IMBDMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IMBDMoviesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
